spring:
    h2:
        console:
            path: /h2-console
            enabled : true
    jpa:
        generate-ddl: false
        show-sql: true
        hibernate:
            ddl-auto: none
    datasource:
        platform: h2
        schema: classpath:sql/schema.sql
        data: classpath:sql/data.sql
    application:
        name: springCloudTestProv
        
eureka:
    client:
        serviceUrl:
            defaultZone: http://192.168.50.12:8761/eureka
    instance:
        #prefer-ip-address: true
        hostname: 192.168.50.12